name: ClaimEase
on:
 push:
    branches:
      - '**'
 pull_request:
    branches:
      - '**'
 workflow_dispatch:

jobs:
 my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for code changes
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only ${{ github.base_ref }} ${{ github.sha }} > changes.txt
          if [ -s changes.txt ]; then
            echo "Changes detected:"
            cat changes.txt
          else
            echo "No changes detected."
          fi

      - name: my-step
        run: echo "ClaimEase" this is my CI.yml which I use for CI in GitHub.
